
# SEO settings
title: "Orthogonally Related"
title2: "" # default: ""
description: "Yet another blog"
keywords: "blog, math, biology, research, data science"
url: http://danielwo.github.io/ # site url
# baseurl: "/thinkspace" # apply repo name if use it under gh-pages branch
baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: https://github.com/danielwo/danielwo.github.io
disqus_shortname: "danielwo-github-io"
twitter_username: "doct0r_dan"
comments: true 

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Daniel Wood"
  job      : "Mathematician"
  bio      : "I do data science-y stuff."
  thumb    : /images/me.jpg
  email    : danwoodphd@gmail.com
  url      : http://danielwo.github.io
  github   : http://github.com/danielwo
  twitter  : http://twitter.com/doct0r_dan
  facebook : https://www.facebook.com/daniel.wood.353803
  linkedin : https://www.linkedin.com/in/danieltwood/

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@doct0r_dan"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : bio
    title: Bio
  - slug : blog
    title: Blog
  - slug : github
    title: Github

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
